#!/usr/bin/env bash
#Display "Best School 10 times and on the 9th display also "Hi" on the next line

count=0
while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	
	echo "Best School"
	((count++))
done
