#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

if [ "$EUID" -ne 0]
then
	echo "Please run as root or use sudo"
	exit 1
fi

cp /etc/hosts ~/etc/hosts.old
echo "127.0.0.2 localhost" > ~/etc/hosts.old
echo "8.8.8.8 facebook.com >> ~/etc/hosts.old
cp -f ~/etc/hosts.old /etc/hosts
