#!/usr/bin/env bash
# Run Nginx as Nginx

# Modify NGINX configuration
chmod ugo+wrx /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Restart NGINX
service nginx restart
